### ISSUE TITLE
Change camera

### ISSUE THREAD

**Issue by bdblaere** [AIRLegend/aitracker#14]
Is there a way to change the input source (camera)?
I have two camera's (the default camera and an external one), but I don't see a way to select the second camera in AITracker.

**Comment by bdblaere** [comment]
Disabling the other camera does make it work.
(Thanks for the suggestion on Discord  @AIRLegend)

**Comment by AIRLegend** [comment]
(Awswered on Discord)

That's not implemented right now, however, as a temporary fix, disabling your internal camera via Windows Device Manager might do the trick.
